name: Build and test container images

on:
  push:
  pull_request:
  repository_dispatch:
    types:
      - dispatch-build
  workflow_dispatch:

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ['el8', 'al8', 'cuda_11_8_0']
        osg_series: ['3.6']
        repo: ['development', 'testing', 'release']
    steps:
      - id: custom-image-name
        env:
          SERIES: ${{ matrix.osg_series }}
          REPO: ${{ matrix.repo }}
          OS: ${{ matrix.os }}
        run: |
          PREFIX="output_image=${GITHUB_REPOSITORY}:${SERIES}"
          if [[ $OS == 'el8' ]]; then
            echo "${PREFIX}-${REPO}" >> ${GITHUB_OUTPUT}
          else
            echo "${PREFIX}-${OS}-${REPO}" >> ${GITHUB_OUTPUT}
          fi

      - id: build-image
        uses: opensciencegrid/build-container-action@v0.5.0
        with:
          osg_series: ${{ matrix.osg_series }}
          osg_repo: ${{ matrix.repo }}
          base_os: ${{ matrix.os }}
          output_image: ${{ steps.custom-image-name.outputs.output_image }}

      - name: Docker + CVMFS bindmount
        env:
          CONTAINER_IMAGE: ${{ steps.build-image.outputs.tags }}
        run: |
          sudo ./tests/test_inside_gha.sh docker \
                                          bindmount \
                                          "$CONTAINER_IMAGE"

      - name: Docker + cvmfsexec
        env:
          CONTAINER_IMAGE: ${{ steps.build-image.outputs.tags }}
        run: |
          sudo ./tests/test_inside_gha.sh docker \
                                          cvmfsexec \
                                          "$CONTAINER_IMAGE"

      - name: Singularity + CVMFS bindmount
        env:
          CONTAINER_IMAGE: ${{ steps.build-image.outputs.tags }}
        run: |
          sudo ./tests/test_inside_gha.sh singularity \
                                          bindmount \
                                          "$CONTAINER_IMAGE"
